version: "3.9"

services:
  db:
    image: postgres:15
    container_name: getmo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: M!@miheat2707
      POSTGRES_DB: getmo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: getmo_backend
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:M!@miheat2707@db:5432/getmo"
      JWT_SECRET: "supersecretgetmopassword123"

volumes:
  pgdata:
